pub(crate) mod finnish;
#[cfg(feature = "grammar")]
pub mod grammar;
#[cfg(feature = "handle")]
pub mod handle;
#[cfg(feature = "hyphenate")]
pub mod hyphenator;
#[cfg(feature = "analyze")]
pub mod morphology;
#[cfg(feature = "spell")]
pub mod speller;
#[cfg(feature = "suggest")]
pub mod suggestion;
pub mod tokenizer;
